export const PROJECTS = [
  {
    id:          'Archivon',
    num:         '01',
    badge:       'THESIS · KTH 2026',
    status:      'Done!',
    title:       'Archivon',
    description: 'A production-grade AI documentation pipeline built as my thesis project at KTH in collaboration with Epinova. Ingests development activity from GitHub and Azure DevOps, generates vector embeddings, and surfaces intelligent feature summaries through a dual-protocol API (REST + MCP). Two independent ASP.NET Core services deployed on Azure App Service with full CI/CD.',
    tags:        ['RAG', 'Azure OpenAI', 'pgvector', 'C#', '.NET 10', 'Docker', 'MCP Protocol', 'PostgreSQL', 'Azure DevOps'],
    image:       '/assets/img/archivon.png',
    imageAlt:    'Archivon architecture diagram',
    reversed:    false,
  },
  {
    id:          'wait-app',
    num:         '02',
    badge:       null,
    status:      null,
    title:       'Admin Panel for Patient Overview System',
    description: 'Developed an admin panel for patient data management with secure authentication, REST APIs, and real-time blood pressure charts featuring search and sort functionality.',
    tags:        ['React', 'TypeScript', 'Java', 'Keycloak', 'PostgreSQL', 'Docker'],
    githubUrl:   'https://github.com/Wait-app-KTH/Admin-Panel-for-Wait-App-Patient-Overview-System-for-KI',
    image:       '/projects/waitApp.png',
    imageAlt:    'Admin Panel for Patient Overview System',
    reversed:    true,
  },
  {
    id:          'ball-brawl',
    num:         '03',
    badge:       null,
    status:      null,
    title:       'Ball Brawl — Network Based 2D Multiplayer Game',
    description: 'Developed a 2D multiplayer soccer game for up to four players, implementing game mechanics and MVC architecture to create a stable, responsive prototype.',
    tags:        ['C', 'SDL2', 'TCP/IP', 'MVC', 'Scrum'],
    githubUrl:   'https://github.com/eyepat/Ball-Brawl-Network-Based-2D-Multiplayer-Game',
    image:       '/projects/BallBrawl.png',
    imageAlt:    'Ball Brawl multiplayer game',
    reversed:    false,
  },
  {
    id:          'drive-my-kid',
    num:         '04',
    badge:       null,
    status:      null,
    title:       'Drive My Kid — Carpooling Prototype for Children',
    description: 'Designed a mobile app for parental carpooling using Figma, incorporating user testing and needs analysis to create a clickable prototype with intuitive UI and built-in safety features.',
    tags:        ['Figma', 'UX Research', 'Usability Testing', 'Design Thinking'],
    githubUrl:   null,
    image:       '/projects/DriveMyKids.png',
    imageAlt:    'Drive My Kid carpooling app',
    reversed:    true,
  },
  {
    id:          'eyepat-combat',
    num:         '05',
    badge:       null,
    status:      null,
    title:       'Eyepat-Combat — 2D Fighting Game',
    description: 'Created a 2D fighting game in Unity inspired by Mortal Kombat, featuring character animations, health bars, attack combos, and game UI. This project sparked my passion for game development and helped me understand visual effects, hit detection, and combat mechanics.',
    tags:        ['Unity', 'ASP.NET', '2D Animation', 'Game Physics', 'UI Design'],
    githubUrl:   'https://github.com/eyepat/Eyepat-Combat-game.git',
    image:       '/projects/EyePat-Combat.png',
    imageAlt:    'Eyepat-Combat 2D fighting game',
    reversed:    false,
  },
];
